name: "upload"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "**.json"
      - "README.md"
      - ".github/workflows/upload.yml"
      - "!serverless/**"
      - "!scheduler.py"
      - "!ql_update.py"

concurrency:
  group: upload-workflow
  cancel-in-progress: true

jobs:
  upload-files:
    if: github.repository == 'chen310/NeteaseCloudMusicTasks'
    name: upload
    runs-on: ubuntu-latest
    steps:
      - name: Clone local repository
        uses: actions/checkout@v2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: |
            ./
            !./.git/
            !./.github/
            !./public/
            !./serverless/
            !./.dockerignore
            !./.gitignore
            !./requirements.txt
            !./Dockerfile
            !./ql_update.py
            !./scheduler.py
